###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Self-Hosted Runner Test

on: 
  push:
    branches:
    - githubactions

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: docker build python
      run: |
        docker build ./python/introduction/ -t python:1.0.0